version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: chatllm-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: chatllm
      POSTGRES_PASSWORD: chatllm
      POSTGRES_DB: chatllm
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:

# docker compose up -d
# exec
# docker exec -it chatllm-postgres bash
# psql -U chatllm -- User chatllm
# \c chatllm --connect database chatllm
#   \q         -- ออก
#   \du        -- ดู roles
#   \l         -- ดู databases
#   \dt        -- ดู tables